using System;

namespace ResumeBuilderApp
{
	public class ResumeBuilder
	{
        private Resume _resume = new Resume(); //instantiate Resume class privately
        private string? title = "\nWelcome to the Resume Builder\n";
        private string? choice;

        public void Start()
        {
            while (true)
            {
                Start:
                Console.ForegroundColor = ConsoleColor.Blue; // Set text color to green
                Console.WriteLine(title);
                Console.ResetColor();

                Console.ForegroundColor= ConsoleColor.Yellow;
                Console.WriteLine("=============================================================================="); Console.ResetColor();

                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("1. Build Resume");
                Console.WriteLine("2. Edit Existing Resume (Must be generated by this program before)");
                Console.WriteLine("3. Exit");
                Console.ResetColor();

                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine("=============================================================================="); Console.ResetColor();

                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write("\nChoice: "); 
                choice = Console.ReadLine(); Console.ResetColor();

                switch(choice)
                {
                    case "1":
                        Console.ForegroundColor = ConsoleColor.Yellow;
                        _BuildNewResume();
                        Console.ResetColor();
                        break;
                    case "2":
                        _EditExistingResume();
                        break;
                    case "3":
                        Console.Clear();
                        Console.WriteLine("\nExiting Resume Builder...");
                        return;
                    default:
                        Console.Clear();
                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.WriteLine("Invalid option. Please choose again."); Console.ResetColor();
                        goto Start;
                }

            response:
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.Write("\nWould you like to try again? (y/n): ");
                choice = Console.ReadLine();
                if (choice == "y")
                {
                    Console.Clear();
                    Console.WriteLine("Restarting Program.....");
                    continue;
                }
                else if (choice == "n")
                {
                    Console.Clear();
                    Console.WriteLine("Thanks for using my program!");
                    Console.ResetColor();
                    break;
                }
                else
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine("Invalid input. Try again!"); Console.ResetColor();
                    goto response;
                }

            }
        }
       
        private void _BuildNewResume() //For generating a new resume from scratch
        {
            Console.Clear();
            Console.WriteLine("Collecting Resume Data....Yipee\n");

            _resume = new Resume();
            try
            {
                // Collect data for each section
                Console.WriteLine(title);
                Console.WriteLine("==============================");
                Console.WriteLine("     PERSONAL INFORMATION");
                Console.WriteLine("==============================\n");
                _resume.PersonalInfo.CollectData();
                Console.Clear();

                Console.WriteLine(title);
                Console.WriteLine("==============================");
                Console.WriteLine("       WORK EXPERIENCE");
                Console.WriteLine("==============================\n");
                _resume.WorkExperience.CollectData();
                Console.Clear();

                Console.WriteLine(title);
                Console.WriteLine("==============================");
                Console.WriteLine("          EDUCATION");
                Console.WriteLine("==============================\n");
                _resume.Education.CollectData();
                Console.Clear();


                Console.WriteLine(title);
                Console.WriteLine("==============================");
                Console.WriteLine("           SKILLS");
                Console.WriteLine("==============================\n");
                _resume.Skills.CollectData();
                Console.Clear();

            }
            catch (Exception ex)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("\nError caught: " + ex.Message);
                Console.ResetColor();
            }

            Console.ForegroundColor = ConsoleColor.Cyan;
            _ExportAndEdit();
        }

        private void _EditExistingResume() //editing existing resume
        {
            Console.Clear();
            Console.WriteLine("Loading existing resume....\n");

            //load the resume
            _resume = FileHandler.LoadFromTxtFile();

            if (_resume == null) //checks if the FileHandler returns null or not
            {Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("\nCould not load resume.Returning to main menu....\n"); Console.ResetColor();
                return;
            }

            Console.ReadKey();

            Console.WriteLine();

            _ExportAndEdit();
        }

        private void _ExportAndEdit()
        {
            while(true)
            { 
                Console.Clear();
                Console.WriteLine(title);

                Console.WriteLine("|Current Resume Data|");

            choices:
                _DisplayResume(); // Display the collected information
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("What would you like to do?");
                Console.WriteLine("1. Edit a section");
                Console.WriteLine("2. Export Current Generated Resume");
                Console.WriteLine("3. Exit");
                Console.Write("Choice: ");
                choice = Console.ReadLine();
                Console.ResetColor();
                switch (choice)
                {
                    case "1":
                        try
                        {
                            _EditSection();
                        }
                        catch (Exception ex)
                        {
                            Console.ForegroundColor = ConsoleColor.Red;
                            Console.WriteLine("\nError caught: " + ex.Message); Console.ResetColor(); continue; 
                        }
                        goto choices;
                    case "2":
                        Console.Clear();
                        Console.ForegroundColor = ConsoleColor.Blue;
                        Console.WriteLine(title); Console.ResetColor();
                        Console.ForegroundColor = ConsoleColor.Cyan;
                        FileHandler.SaveToFile(_resume);
                        Console.ResetColor();
                        return;
                    case "3":
                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.WriteLine("\nExiting Resume Builder....."); Console.ResetColor();
                        return;
                    default:
                        Console.Clear();
                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.WriteLine("Invalid option. Please choose again."); Console.ResetColor();
                        goto choices;

                }
            }
        }

        private void _EditSection()
        {
            Console.Clear();

            editChoices:
            Console.WriteLine("\nWhich section would you like to edit?");
            Console.WriteLine("1. Personal Information");
            Console.WriteLine("2. Work Experience");
            Console.WriteLine("3. Education");
            Console.WriteLine("4. Skills");
            Console.Write("Choice: ");
            string? editChoice = Console.ReadLine();

            Console.Clear();
            switch (editChoice)
            {
                case "1":
                    Console.WriteLine("\nEditing Personal Information\n");
                    _resume.PersonalInfo.CollectData();
                    break;
                case "2":
                    Console.WriteLine("\nEditing Work Experience\n");
                    _resume.WorkExperience.CollectData();
                    break;
                case "3":
                    Console.WriteLine("\nEditing Education\n");
                    _resume.Education.CollectData();
                    break;
                case "4":
                    Console.WriteLine("\nEditing Skills\n");
                    _resume.Skills.CollectData();
                    break;
                default:
                    Console.Clear();
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine("Invalid option. Please choose again."); Console.ResetColor();
                    goto editChoices;
            }
        }

        private void _DisplayResume()
        {
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.WriteLine("\nGenerated Resume:\n");

            Console.WriteLine(_resume.PersonalInfo);
            Console.WriteLine(_resume.WorkExperience);
            Console.WriteLine(_resume.Education);
            Console.WriteLine(_resume.Skills);
            Console.ResetColor();
        }
	}
}